services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:4000' 
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public" 
      JWT_SECRET: ${JWT_SECRET}
      BASE_URL: ${BASE_URL}
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

volumes:
  postgres_data: